name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 3.0.1
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://github.com/rushio-consulting/flutter_camera_ml_vision

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.12.0+1
    #git:
    #  url: git://github.com/algirdasmac/flutterfire
    #  path: packages/firebase_ml_vision
  firebase_core: ^0.5.0+1
  visibility_detector: ^0.2.0
  path_provider: any
  pedantic: ^1.11.0
  device_info: ^1.0.0
  camera: any
  collection: ^1.15.0
  shared_preferences: ^0.5.12+4
  shared_preferences_windows: any

dev_dependencies:
  flutter_test:
    sdk: flutter
    
